name: Deploy Website to S3

on:
  push:
    branches:
      - production  # or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # or 'npm run dev' if that’s your build command

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Ensure AWS region is correctly passed

    - name: Sync S3 Bucket
      run: |
        aws s3 sync ./dist s3://tanzeembhatkal.com --delete